### ISSUE TITLE
How does `mixl` parse the matrix of draws over the different individuals in the sample?

### ISSUE THREAD

**Issue by alvarogutyerrez** [joemolloy/fast-mixed-mnl#7]
Hi all, I've been using `mixl` and I like it a lot because it is the faster way to run mixed logit using R. I am now trying to understand a small issue relate to how the program uses the draws when a matrix of draws is provided. 

First, as far as I understand, the program only allows the user to model heterogeneity across individuals, though not intra-respondent variation (Molloy, Schmid, Becker & Axhausen, 2019; section 5.2 ). This means that the *__same__* draw is used for all the choice scenarios faced by the __same__ individual when computing the product of logit formulas. 

As far as I could see in the source code the programs internally generated Halton draws using: 

```
create_halton_draws <- function (Nindividuals, nDraws, draw_dimensions) 
{
    as.matrix(randtoolbox::halton(Nindividuals * nDraws, draw_dimensions, 
        normal = TRUE))
}
```

Here is my question, when I provide `mixl` with a [(N x D) x K] matrix where N is the number of individuals, D is the number of Draws and K is the number of random parameters, **is the program using the first D rows of the matrix of draws to compute the choice probabilities of the first individual?** If so, where can I check said behavior in the code? I was trying to review the source code, but unfortunately, I am not very familiar with the way that the likelihood is written (using a C++ compiler).

This question is triggered by the fact that I want to use fully antithetic draws when fitting the model so I need to understand how the program parses the matrix of draws in order to correctly simulate my fully antithetic draws. 

To put things concretely, this is what I mean with fully antithetic draws when we include three random parameters in the utility specification (Andersen, 2014)

![image](https://user-images.githubusercontent.com/39359053/149345367-e245464f-e5e9-4bea-863a-4aa7b82f404f.png)

So each set of symmetric draws needs to be assigned to the same individual and **not** distributed over different individuals. 

I hope my explanation was clear enough. If it was not please do not hesitate to ask for further clarifications. 

Thank you in advance for your time and also for writing such an amazing package!

Best :)

**References**

* Andersen, L. M. (2014). Obtaining reliable likelihood ratio tests from simulated likelihood functions. PloS one, 9(10), e106136.

* Molloy, J., Schmid, B., Becker, F., & Axhausen, K. W. (2019). mixl: An open-source R package for estimating complex choice models on large datasets. Arbeitsberichte Verkehrs-und Raumplanung, 1408.

**Comment by joemolloy** [comment]
Great, I'm glad you're enjoying using the package!

The draws are stored in a 2d array, with the first dimension being the D draws for each individual, then the second dimension being the draws for that id and 'draw iteration' . 

so with 100 draws and 4 draw dimensions, the first 100 rows are the 100 draws for the first individual, with 4 columns - one for each draw. Then the second 100 rows for the second individual and so on.

You can see this in the code here:

https://github.com/joemolloy/fast-mixed-mnl/blob/900fff23acd0ca2355daa1d6f9b86d233410fdb5/inst/include/mixl/loglik.cpp#L104

**Comment by alvarogutyerrez** [comment]
I am sorry for the delay, idk why I did not get a notification from your response. 

That was incredibly useful. Thank you a lot !!!
